name: Release

on:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/**"

permissions:
  contents: read

jobs:
  publish-image:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: ubuntu-22.04

    permissions:
      id-token: write # This is the key for OIDC cosign!
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - id: get_version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/!!p')
          echo "::set-output name=release_version::$RELEASE_VERSION"
      - name: Get Docker tags
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/loft-sh/loft-router
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: loft-sh
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: Install DevPod
        run: |
          curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && \
              sudo install -c -m 0755 devpod /usr/local/bin && \
              rm -f devpod
      - name: Build PreBuild
        run: |
          # Add local docker provider
          devpod provider add docker
          
          # Build image via local docker
          devpod build . --repository ghcr.io/loft-sh/devpod-kubebuilder-template
